version: '3.8'

services:
  app:
    build: .
    container_name: portfolio-app
    restart: unless-stopped
    networks:
      - portfolio-network
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    volumes:
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    ports:
      - "8000:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  app-dev:
    build: 
      context: .
      target: base
    container_name: portfolio-app-dev
    restart: unless-stopped
    networks:
      - portfolio-network
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/database/database.sqlite
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
      - ./database:/var/www/database
    ports:
      - "8001:80"
    command: php artisan serve --host 0.0.0.0 --port 80

networks:
  portfolio-network:
    driver: bridge
