services:
  - type: web
    name: portfolio-laravel
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile.prod
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: APP_TIMEZONE
        value: UTC
      - key: APP_LOCALE
        value: en
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/database/database.sqlite
      - key: DB_FOREIGN_KEYS
        value: true
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_SECURE_COOKIES
        value: true
      - key: SESSION_SAME_SITE
        value: lax
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: error
      - key: FILESYSTEM_DISK
        value: local
      - key: BROADCAST_DRIVER
        value: log
    healthCheckPath: /health