services:
  - type: web
    name: laravel-backend
    env: php
    plan: free
    buildCommand: |
      # Install PHP dependencies
      composer install --optimize-autoloader --no-dev
      # Install frontend dependencies (if using npm or yarn)
      npm install
      # Build assets
      npm run production
      # Generate application key
      php artisan key:generate
      # Run migrations (optional)
      php artisan migrate --force
    startCommand: |
      # Start the Laravel server
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_KEY
        value: base64:lincoln-app-key
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://lincoln-portfolio.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_database_name
      - key: DB_USERNAME
        value: your_database_user
      - key: DB_PASSWORD
        value: your_database_password
